### PR TITLE
`@remotion/lambda`: Add getAwsClient() to Light ciient

### LINKED ISSUE #3090: Failed to compile `compositor-linux-x64-gnu/compositor` when using `getAwsClient()`
I was trying to use the code snippet of the docs regarding presigned URLs. The `getAwsClient` function triggers the following error:

Failed to compile:
```
./node_modules/@remotion/compositor-linux-x64-gnu/compositor
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
```

I am using Ubuntu 22.04.3 LTS.

```
Import trace for requested module:
./node_modules/@remotion/compositor-linux-x64-gnu/compositor
./node_modules/@remotion/compositor-linux-x64-gnu/index.js
./node_modules/@remotion/renderer/dist/compositor/get-executable-path.js
./node_modules/@remotion/renderer/dist/index.js
./node_modules/@remotion/lambda/dist/api/download-media.js
./node_modules/@remotion/lambda/dist/index.js
```

### PR DESCRIPTION
**Pull request by JonnyBurger**
Fixes #3090

### CODE REVIEW

File: packages/lambda/src/client.ts [hunk 1]
```diff
@@ -26,6 +26,7 @@ import type {AwsRegion} from './pricing/aws-regions';
 import type {RenderProgress} from './shared/constants';
 import type {WebhookPayload} from './shared/invoke-webhook';
 
+export {CustomCredentials, getServiceClient} from './shared/aws-clients';
```
Comment (mecirmartin) [inline packages/lambda/src/client.ts:29]: This export `getServiceClient` instead of `getAwsClient` 

Consequently `import { getAwsClient } from "@remotion/lambda/client";` doesn't work
@JonnyBurger
